// Per-agent knowledge base — used by the interactive chat in the agent detail card.
// Each agent has an intro, capabilities, sample Q&A patterns, and a fallback.
// The chat matches keywords in user input against `kb[*].keywords` and replies.

const builder = (name, intro, kb, fallback) => ({
  name,
  intro,
  kb,
  fallback,
});

export const AGENT_KB = {
  Ava: builder(
    "Ava",
    "Hi, I'm Ava — your Sales Agent. I qualify leads, run discovery, generate quotes and book demos. How can I help you today?",
    [
      { keywords: ["qualify", "lead", "mql", "sql", "discovery"],
        reply: "I score every inbound enquiry on industry, deal size, urgency and authority. Hot ones I book straight onto your AE's calendar; warm ones I nurture via WhatsApp/email until they're ready." },
      { keywords: ["demo", "meeting", "appointment", "book", "schedule"],
        reply: "Happy to book one. Could you share your name, work email and the use case you're exploring (Voice AI, multi-agent, automation)?" },
      { keywords: ["quote", "price", "pricing", "cost", "estimate"],
        reply: "Pricing depends on agent count, channels and integrations. Share your monthly volume + stack — I'll route a tailored estimate to you within 24h." },
      { keywords: ["crm", "salesforce", "hubspot", "dynamics", "integrate"],
        reply: "Yes — I sync bi-directionally with Salesforce, HubSpot and Dynamics 365 out of the box. Every conversation lands as an activity, contact or opportunity update." },
      { keywords: ["what", "who", "do", "you", "ava"],
        reply: "I'm a Sales Agent — Lead Qualification, Sales Enquiries, Demo Booking and Quote Generation across voice, web chat, WhatsApp and email. Want me to walk you through a sample deployment?" },
    ],
    "Tell me your industry and monthly lead volume — I'll suggest exactly how I can help shorten your sales cycle.",
  ),
  Sophia: builder(
    "Sophia",
    "Hi, I'm Sophia — your Support Agent. I handle tickets across voice, chat and WhatsApp. What can I help with?",
    [
      { keywords: ["ticket", "support", "triage", "case"],
        reply: "I triage every incoming ticket — classify intent, urgency, sentiment — and either resolve L1 myself or route to the right human queue with full context." },
      { keywords: ["order", "track", "delivery", "where", "shipment"],
        reply: "Give me the order ID and I'll fetch live status from your TMS/WMS, share an ETA and proactively notify the customer if there's a delay." },
      { keywords: ["refund", "return", "exchange"],
        reply: "I run your return policy automatically — eligibility check, reverse pickup, refund initiation — all logged into your CRM. No human touch unless an exception." },
      { keywords: ["whatsapp", "chat", "voice", "channel"],
        reply: "I'm omni-channel: voice, web chat, WhatsApp, in-app. Same memory and context across all channels." },
      { keywords: ["what", "who", "sophia"],
        reply: "I'm your Support Agent — Customer Service, Ticket Triage, Order Tracking and Refunds. Typical deflection on L1: 70%. Want a live walk-through?" },
    ],
    "Share the issue your customers usually call about — I'll explain exactly how I'd resolve it.",
  ),
  Iris: builder(
    "Iris",
    "Hello, I'm Iris — your Compliance Agent. I monitor calls, enforce regulatory phrases and produce audit trails. Ask me anything.",
    [
      { keywords: ["qa", "quality", "monitor", "calls"],
        reply: "I score 100% of voice and chat interactions — agent script adherence, mandatory disclosures, sentiment, dead-air. Daily QA report straight to your team lead." },
      { keywords: ["regulatory", "regulation", "compliance", "disclosure"],
        reply: "I check for industry mandates (IRDAI, RBI, GDPR, HIPAA) in real time and alert the agent if a disclosure is missing — before the call ends." },
      { keywords: ["audit", "log", "trail", "report"],
        reply: "Every interaction is logged with timestamps, transcripts and risk scores. Exportable to your audit system any time." },
      { keywords: ["risk", "fraud", "detect"],
        reply: "I flag risk signals — false promises, mis-selling, KYC gaps — and escalate to your risk manager within seconds." },
      { keywords: ["what", "who", "iris"],
        reply: "I'm your Compliance Agent — Call QA, Regulatory Checks, Audit Trails and Risk Detection. 100% coverage, real-time." },
    ],
    "What regulation are you working under? I'll explain how I help you stay 100% compliant.",
  ),
  Neo: builder(
    "Neo",
    "Hey, I'm Neo — your Research Agent. I synthesize briefs from public data, your docs and your CRM. What do you need?",
    [
      { keywords: ["competitor", "market", "research", "intel"],
        reply: "Give me a competitor or market — I'll return a brief with positioning, recent funding, pricing signals, tech moats and notable customer wins in a few minutes." },
      { keywords: ["brief", "summarise", "summarize", "summary"],
        reply: "Drop a deck/PDF/URL and I'll produce an exec brief with key takeaways, contradictions and follow-up questions." },
      { keywords: ["data", "synth", "insight"],
        reply: "I work across your CRM (deal stages), web data (intent signals) and internal docs (notes, calls). I surface patterns humans miss." },
      { keywords: ["what", "who", "neo"],
        reply: "Research Agent — Market Research, Data Synthesis, Competitor Tracking, Briefings. Typical time saved: 12 hours per week per analyst." },
    ],
    "Tell me what you'd love to know about a market or competitor — I'll show you my research style.",
  ),
  Atlas: builder(
    "Atlas",
    "Hi, I'm Atlas — your Operations Agent. I run workflows across CRM, ERP and telephony. How can I help?",
    [
      { keywords: ["invoice", "ap", "payable", "process"],
        reply: "I OCR invoices, do 3-way PO match, validate GST/VAT, route approvals and schedule payments. Exception-only attention from your AP team." },
      { keywords: ["workflow", "automation", "approve", "approval"],
        reply: "Tell me the process — vendor onboarding, leave approvals, CapEx — I orchestrate it across your existing systems with audit trails." },
      { keywords: ["crm", "sync", "update", "data"],
        reply: "I keep your CRM, ERP and BI dashboards in sync — no double entry, no stale data." },
      { keywords: ["report", "status", "update"],
        reply: "I generate the weekly ops update — KPIs, exceptions, action items — and ping it to your team's Slack/Teams every Monday 9 AM." },
      { keywords: ["what", "who", "atlas"],
        reply: "Operations Agent — Workflow Automation, Invoice Automation, CRM Sync, Approvals. Typical cycle-time reduction: 60%." },
    ],
    "Pick a process — I'll explain how I'd automate it on your existing stack.",
  ),
  Mira: builder(
    "Mira",
    "Hi, I'm Mira — Content Moderator. I review user content at scale. What policy are you trying to enforce?",
    [
      { keywords: ["content", "post", "review", "moderate"],
        reply: "I review text, images and videos in real time against your policy — hate speech, nudity, fraud, spam, regulated content — with human-in-the-loop for edge cases." },
      { keywords: ["policy", "guideline", "rule"],
        reply: "Upload your content policy doc — I learn it and apply it consistently 24/7. Updates take minutes, not weeks." },
      { keywords: ["spam", "fraud", "fake"],
        reply: "I detect bot patterns, fake accounts, coordinated inauthentic behaviour. Auto-action or escalate based on confidence." },
      { keywords: ["what", "who", "mira"],
        reply: "Content Moderator — Content Review, Image Moderation, Policy Enforcement, Spam Filtering. 97.4% precision." },
    ],
    "What type of platform are you moderating (marketplace, social, media)? I'll explain my approach.",
  ),
  Kai: builder(
    "Kai",
    "Hi, I'm Kai — Production Planning Agent. I schedule runs, optimise capacity and flag bottlenecks. Ask me anything about your shop floor.",
    [
      { keywords: ["plan", "schedule", "production", "shift"],
        reply: "I generate a daily/weekly plan from demand forecast, machine availability, BOM and material readiness. Optimised for OEE and on-time delivery." },
      { keywords: ["oee", "capacity", "utilisation", "utilization"],
        reply: "I track OEE in real time — Availability × Performance × Quality — and recommend changeovers to lift overall throughput by 10-15%." },
      { keywords: ["bom", "material", "shortage", "stockout"],
        reply: "I cross-check BOM against inventory; if a material gap is forecast, I flag alternative SKUs or suggest a pull-in from a sister plant." },
      { keywords: ["erp", "sap", "oracle", "dynamics"],
        reply: "I sit on top of SAP S/4HANA, Oracle JDE and Dynamics 365 SCM — no rip-and-replace." },
      { keywords: ["what", "who", "kai"],
        reply: "Production Planning Agent — Demand Planning, Shop-floor Scheduling, BOM Analysis, Capacity Optimisation. Typical OEE lift: +14%." },
    ],
    "Tell me about your plant — sector, line count, current OEE — I'll show you my impact.",
  ),
  Luna: builder(
    "Luna",
    "Hi, I'm Luna — Designer Agent for fashion. I generate trend-aligned design briefs, mood boards and tech-pack drafts. What season are we working on?",
    [
      { keywords: ["trend", "forecast", "season"],
        reply: "I track runway, Pinterest, Instagram, Lyst and your sell-through data. I surface emerging colour, silhouette and material trends 8-12 weeks before peers." },
      { keywords: ["mood", "board", "concept"],
        reply: "Give me a mood (e.g., 'Gen-Z India · monsoon · romantic') — I generate a mood board with palette, fabric and reference imagery in minutes." },
      { keywords: ["tech", "pack", "spec"],
        reply: "I draft a tech-pack with construction notes, BOM, target costing and grading. Push to your PLM directly." },
      { keywords: ["plm", "figma", "tool"],
        reply: "I work alongside Figma, Adobe and your PLM. Round-tripping is one-click." },
      { keywords: ["what", "who", "luna"],
        reply: "Designer Agent — Trend Forecasting, Mood Boards, Colour Palettes, Tech-Pack Drafts. Concept-to-PLM: 5× faster." },
    ],
    "Which category and region are we designing for? I'll show you a quick concept.",
  ),
  Ronan: builder(
    "Ronan",
    "Hello, I'm Ronan — Accounts Payable Agent. Invoices in, cash flow optimised, zero leakage. What's your AP volume?",
    [
      { keywords: ["invoice", "ocr", "process"],
        reply: "I OCR every invoice (PDF, email, scan), extract line items, vendor, GST, amount — even from handwritten ones — and validate against the PO." },
      { keywords: ["po", "match", "3-way", "two-way"],
        reply: "I do automated 3-way match (Invoice ↔ PO ↔ GRN). Mismatches are flagged for your AP exec — everything else flows through to payment." },
      { keywords: ["gst", "tax", "vat", "tds"],
        reply: "I validate GSTIN, HSN, tax rates, e-invoice IRN and TDS applicability. Compliance is built-in, not bolted on." },
      { keywords: ["payment", "schedule", "cash"],
        reply: "I schedule payments to optimise your cash position — taking early-payment discounts where ROI > cost of capital." },
      { keywords: ["what", "who", "ronan"],
        reply: "Accounts Payable Agent — Invoice OCR, PO Matching, GST/Tax Validation, Payment Scheduling. Typical processing-cost reduction: 78%." },
    ],
    "Share your monthly invoice volume — I'll show you my expected impact on your AP function.",
  ),
};
