export const ASSETS = {
  mascot: "https://customer-assets.emergentagent.com/job_0cd876a0-a865-4d97-862d-50a9b26ad778/artifacts/89py54a2_Plug%20Avatar.png",
  // Hero — Indian AI digital-workforce avatar (Gemini Nano Banana)
  heroAvatar: "/agents/hero.png",
  // Real customer logos screenshot
  customerLogos: "https://customer-assets.emergentagent.com/job_voice-agent-hub-62/artifacts/ktxf6vj3_Screenshot%202026-06-24%20at%2011.09.37%E2%80%AFPM.png",
  // AI / robotic-looking portraits — generated by Gemini Nano Banana
  agentAva:    "/agents/ava.png",
  agentSophia: "/agents/sophia.png",
  agentIris:   "/agents/iris.png",
  agentNeo:    "/agents/neo.png",
  agentAtlas:  "/agents/atlas.png",
  agentMira:   "/agents/mira.png",
  neuralBg: "https://images.pexels.com/photos/17483871/pexels-photo-17483871.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
};

export const AGENTS = [
  { name: "Ava",    role: "Sales Agent",       img: ASSETS.agentAva,    desc: "Qualifies leads, handles enquiries, books meetings.",
    capabilities: ["Lead Qualification", "Sales Enquiries", "Demo Booking", "Quote Generation"] },
  { name: "Sophia", role: "Support Agent",     img: ASSETS.agentSophia, desc: "Resolves tickets across voice, chat & WhatsApp.",
    capabilities: ["Customer Service", "Ticket Triage", "Order Tracking", "Refunds & Returns"] },
  { name: "Iris",   role: "Compliance Agent",  img: ASSETS.agentIris,   desc: "Monitors conversations for QA & regulatory adherence.",
    capabilities: ["Call QA", "Regulatory Checks", "Audit Trails", "Risk Detection"] },
  { name: "Neo",    role: "Research Agent",    img: ASSETS.agentNeo,    desc: "Synthesises data and produces actionable briefs.",
    capabilities: ["Market Research", "Data Synthesis", "Competitor Tracking", "Briefings"] },
  { name: "Atlas",  role: "Operations Agent",  img: ASSETS.agentAtlas,  desc: "Runs workflows across CRM, ERP and telephony.",
    capabilities: ["Workflow Automation", "Invoice Automation", "CRM Sync", "Approvals"] },
  { name: "Mira",   role: "Content Moderator", img: ASSETS.agentMira,   desc: "Reviews and approves user-generated content at scale.",
    capabilities: ["Content Review", "Image Moderation", "Policy Enforcement", "Spam Filtering"] },
];

import { Briefcase, GraduationCap, Building2, ShoppingBag, Truck, Shield, Store, Headphones } from "lucide-react";

const ICONS = { Manufacturing: Briefcase, Education: GraduationCap, "Real Estate": Building2, "Call Center": Headphones, FMCG: ShoppingBag, Logistics: Truck, Insurance: Shield, Retail: Store };

export const INDUSTRIES = [
  {
    name: "Manufacturing",
    challenge: "Demand forecasting, vendor onboarding, CapEx approvals lag production cycles.",
    solution: "Demand Planning Agent + CapEx Approval Agent on SAP/Dynamics.",
    useCases: ["Demand Planning", "CapEx Approval", "Vendor Onboarding", "QA Compliance"],
    stats: [{ k: "Throughput", v: "+18%" }, { k: "Cycle time", v: "-32%" }],
    roi: "$1.2M annual savings",
  },
  {
    name: "Education",
    challenge: "Inbound admission enquiries spike beyond counsellor capacity.",
    solution: "Admission Voice Agent + WhatsApp follow-up bot connected to CRM.",
    useCases: ["Admissions", "Course Counselling", "Fee Reminders", "Parent FAQs"],
    stats: [{ k: "Application rate", v: "3×" }, { k: "Response time", v: "<30s" }],
    roi: "3× application throughput",
  },
  {
    name: "Real Estate",
    challenge: "Cold leads, missed site visits, slow follow-ups across cities.",
    solution: "Voice AI for lead qualification + CRM-synced site-visit scheduler.",
    useCases: ["Lead Qualification", "Site Visit Booking", "Follow-ups", "Channel Partner Comms"],
    stats: [{ k: "Qualified leads", v: "+42%" }, { k: "Site visits", v: "+27%" }],
    roi: "₹500M+ pipeline influenced",
  },
  {
    name: "Call Center",
    challenge: "High AHT, agent attrition, missed call peaks at scale.",
    solution: "AI Voice Agent for L1 deflection + Live agent assist + Real-time QA.",
    useCases: ["L1 Deflection", "After-Hours Handling", "Agent Assist", "Live QA"],
    stats: [{ k: "Deflection", v: "60%" }, { k: "AHT", v: "-30%" }],
    roi: "Cost per call halved",
  },
  {
    name: "FMCG",
    challenge: "Distributor coverage, field beat plans, store visibility gaps.",
    solution: "DMS automation + Store Delivery agent + AI beat optimisation.",
    useCases: ["Distributor Mgmt", "Store Visits", "SKU Replenishment", "Field Reports"],
    stats: [{ k: "Coverage", v: "+25%" }, { k: "Stockouts", v: "-40%" }],
    roi: "Reach in 2× towns",
  },
  {
    name: "Logistics",
    challenge: "Where-is-my-order calls and exception handling drown ops.",
    solution: "Voice + WhatsApp tracking agent integrated with TMS / WMS.",
    useCases: ["Order Tracking", "Delivery Re-attempts", "POD Capture", "Driver Comms"],
    stats: [{ k: "Deflection", v: "70%" }, { k: "NPS", v: "+18 pts" }],
    roi: "24/7 multilingual support",
  },
  {
    name: "Insurance",
    challenge: "Policy enquiries, renewals, claim status — long IVR waits.",
    solution: "Insurance Voice Agent + Claims Status bot + Renewal nudges.",
    useCases: ["Policy Enquiries", "Renewals", "Claims Status", "KYC Reminders"],
    stats: [{ k: "CSAT", v: "4.8 / 5" }, { k: "Renewals", v: "+22%" }],
    roi: "$100M+ book under AI",
  },
  {
    name: "Retail",
    challenge: "Returns, order status and post-purchase queries overwhelm CX.",
    solution: "Conversational AI on existing CRM + WhatsApp + voice integration.",
    useCases: ["Order Status", "Returns", "Loyalty", "Promo Enquiries"],
    stats: [{ k: "AHT", v: "-50%" }, { k: "CSAT", v: "+1.4 pts" }],
    roi: "24/7 conversational CX",
  },
];

export const INDUSTRY_ICONS = ICONS;


const SI = (slug) => `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug}.svg`;
export const INTEGRATIONS = [
  { name: "Microsoft Dynamics",  slug: "dynamics365",      color: "#002050", logo: SI("dynamics365") },
  { name: "Salesforce",          slug: "salesforce",       color: "#00A1E0", logo: SI("salesforce") },
  { name: "HubSpot",             slug: "hubspot",          color: "#FF7A59", logo: SI("hubspot") },
  { name: "SAP",                 slug: "sap",              color: "#0FAAFF", logo: SI("sap") },
  { name: "Oracle",              slug: "oracle",           color: "#F80000", logo: SI("oracle") },
  { name: "WhatsApp",            slug: "whatsapp",         color: "#25D366", logo: SI("whatsapp") },
  { name: "Twilio",              slug: "twilio",           color: "#F22F46", logo: SI("twilio") },
  { name: "Microsoft Azure",     slug: "microsoftazure",   color: "#0078D4", logo: SI("microsoftazure") },
  { name: "OpenAI",              slug: "openai",           color: "#000000", logo: SI("openai") },
  { name: "Power Automate",      slug: "powerautomate",    color: "#0066FF", logo: SI("powerautomate") },
  { name: "Slack",               slug: "slack",            color: "#4A154B", logo: SI("slack") },
  { name: "Zapier",              slug: "zapier",           color: "#FF4A00", logo: SI("zapier") },
];

export const BYOP = [
  { label: "CRM",       full: "Bring Your Own CRM",       desc: "Plug into existing customer data.",      slug: "salesforce" },
  { label: "ERP",       full: "Bring Your Own ERP",       desc: "Access business systems securely.",      slug: "sap" },
  { label: "Workflow",  full: "Bring Your Own Workflow",  desc: "Wrap your processes with AI.",           slug: "zapier" },
  { label: "API",       full: "Bring Your Own API",       desc: "Connect anything via APIs.",             slug: "postman" },
  { label: "Telephony", full: "Bring Your Own Telephony", desc: "Use your call infrastructure.",          slug: "twilio" },
  { label: "Interface", full: "Bring Your Own Interface", desc: "Keep your existing UI.",                 slug: "figma" },
];

export const METRICS = [
  { value: 20, suffix: "+", label: "Projects Delivered" },
  { value: 30, suffix: "+", label: "AI Agents Deployed" },
  { value: 8,  suffix: "",  label: "Countries Served" },
  { value: 12, suffix: "+", label: "Enterprise Customers" },
  { value: 4.8,suffix: "",  label: "Average CSAT", decimals: 1 },
];

// Customers featured (matches uploaded logo image)
export const CUSTOMERS = [
  "Teleperformance", "Konica Minolta", "UltraTech Cement", "Godrej",
  "Bisleri", "Standard Chartered", "Dubai World Trade Centre", "PVR Cinemas",
  "Adidas", "India Today Group", "Hindustan Times", "Pepperfry",
  "King's College Hospital", "Welspun", "BLS International", "Singapore Post",
  "FLoT", "Naukri.com", "STIC Travel Group", "Avon", "Annik", "Wave Infratech",
];
